//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Category_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Level { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<System.DateTime> Date_create { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
