//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int News_ID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<System.DateTime> DateUpload { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<bool> Is_savedraft { get; set; }
        public Nullable<int> Views { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }
    }
}
