//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CartDetails = new HashSet<CartDetail>();
        }
    
        public int Product_ID { get; set; }
        public string Name { get; set; }
        public int Category_ID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateUpload { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> NumberInStock { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<decimal> Price_promotion { get; set; }
        public Nullable<bool> Is_active { get; set; }
        public Nullable<bool> Is_savedraft { get; set; }
    
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual Category Category { get; set; }
    }
}
